import type { VehicleType } from "@/types/vehicles";

export const DEFAULT_VEHICLES: VehicleType[] = [
  {
    id: "firanka",
    name: "Firanka",
    payloadKg: 24000,
    maxLengthM: 13.6,
    avgFuelConsumptionPer100Km: 30,
    costPerKm: 1.45,
    driverCostPerHour: 58,
    driverCostPerDay: 460,
    driverCostPerKm: 0.75,
    driverCostModel: "hourly",
    avgOperationalSpeedKmh: 62,
    tollCostPerKmDomestic: 0.42,
    tollCostPerKmInternational: 0.58,
    stopCostPln: 120,
    defaultMarginPercent: 14,
    active: true
  },
  {
    id: "platforma",
    name: "Platforma",
    payloadKg: 26000,
    maxLengthM: 14,
    avgFuelConsumptionPer100Km: 32,
    costPerKm: 1.6,
    driverCostPerHour: 62,
    driverCostPerDay: 500,
    driverCostPerKm: 0.8,
    driverCostModel: "hourly",
    avgOperationalSpeedKmh: 60,
    tollCostPerKmDomestic: 0.46,
    tollCostPerKmInternational: 0.64,
    stopCostPln: 140,
    defaultMarginPercent: 16,
    active: true
  },
  {
    id: "niskopodwoziowa",
    name: "Naczepa niskopodwoziowa",
    payloadKg: 40000,
    maxLengthM: 18,
    avgFuelConsumptionPer100Km: 38,
    costPerKm: 2.1,
    driverCostPerHour: 78,
    driverCostPerDay: 650,
    driverCostPerKm: 1.1,
    driverCostModel: "daily",
    avgOperationalSpeedKmh: 54,
    tollCostPerKmDomestic: 0.72,
    tollCostPerKmInternational: 0.95,
    stopCostPln: 220,
    defaultMarginPercent: 18,
    active: true
  },
  {
    id: "zestaw-przestrzenny",
    name: "Zestaw przestrzenny",
    payloadKg: 22000,
    maxLengthM: 15.4,
    avgFuelConsumptionPer100Km: 31,
    costPerKm: 1.5,
    driverCostPerHour: 60,
    driverCostPerDay: 480,
    driverCostPerKm: 0.78,
    driverCostModel: "hourly",
    avgOperationalSpeedKmh: 61,
    tollCostPerKmDomestic: 0.44,
    tollCostPerKmInternational: 0.6,
    stopCostPln: 130,
    defaultMarginPercent: 15,
    active: true
  },
  {
    id: "solowka",
    name: "Solówka",
    payloadKg: 10000,
    maxLengthM: 9.2,
    avgFuelConsumptionPer100Km: 21,
    costPerKm: 1.2,
    driverCostPerHour: 50,
    driverCostPerDay: 380,
    driverCostPerKm: 0.64,
    driverCostModel: "hourly",
    avgOperationalSpeedKmh: 58,
    tollCostPerKmDomestic: 0.32,
    tollCostPerKmInternational: 0.47,
    stopCostPln: 80,
    defaultMarginPercent: 12,
    active: true
  },
  {
    id: "specjalny",
    name: "Pojazd specjalny",
    payloadKg: 30000,
    maxLengthM: 16.5,
    avgFuelConsumptionPer100Km: 35,
    costPerKm: 2.4,
    driverCostPerHour: 84,
    driverCostPerDay: 700,
    driverCostPerKm: 1.2,
    driverCostModel: "perKm",
    avgOperationalSpeedKmh: 50,
    tollCostPerKmDomestic: 0.68,
    tollCostPerKmInternational: 0.9,
    stopCostPln: 250,
    defaultMarginPercent: 20,
    active: true
  }
];

export const findVehicleById = (vehicleId: string): VehicleType | undefined =>
  DEFAULT_VEHICLES.find((vehicle) => vehicle.id === vehicleId);
